### ISSUE TITLE
Filter suggestion: unset attributes from variation sku generator

### ISSUE THREAD

**Issue by shanisherf** [godaddy-wordpress/woocommerce-product-sku-generator#30]
Hi,

Small and simple filter allows developers to unset attribute they don't want in `generate_variation_sku()` function.
Adding something like `$variation = apply_filters('wc_sku_generator_unset_attributes', $variation)` in line [318](https://github.com/skyverge/woocommerce-product-sku-generator/blob/master/woocommerce-product-sku-generator.php#L318) can do the job. (tested already)

Then use something like this in theme functions.php
```
add_filter('wc_sku_generator_unset_attributes', 'my_sku_variation_sku_format', 10, 1);

function my_sku_variation_sku_format($variation)
{
    unset($variation['attributes']['attribute_pa_color']);
    return $variation;
}
```

**Comment by unfulvio-godaddy** [comment]
thanks for your request @shanisherf -- a `wc_sku_generator_variation_attributes` filter has been added as part of the 2.5.0 release, please feel free to reopen the issue if you need to submit additional feedback
