### ISSUE TITLE
The Plugin WooCommerce Product SKU Generator has been removed from wordpress.org

### ISSUE THREAD

**Issue by gottschild** [godaddy-wordpress/woocommerce-product-sku-generator#33]
Hello, i got a Wordfence notification:
Critical Problems: The Plugin “WooCommerce Product SKU Generator” has been removed from wordpress.org.

On Wordpress https://wordpress.org/plugins/woocommerce-product-sku-generator/
"This plugin has been closed as of June 9, 2022 and is not available for download. This closure is temporary, pending a full review."

Is that because it has not been updated for a while or is there a security issue? Thanks for help!

**Comment by bekarice** [comment]
hey @gottschild @dirktolken  working on getting this relisted! we had an issue with our developer account email so now that it's resolved we're pushing an update to get this made available again, just having trouble getting that code live -- stay tuned!

**Comment by dirktolken** [comment]
> hey @gottschild @dirktolken working on getting this relisted! we had an issue with our developer account email so now that it's resolved we're pushing an update to get this made available again, just having trouble getting that code live -- stay tuned!

Awesome thanks!

**Comment by unfulvio-godaddy** [comment]
This has since been relisted last year so I am going to close this issue -- thanks everybody for reporting the issue
